### PR TITLE
style: :art: run prettier on the codebase

### PR DESCRIPTION
**Pull request by brettgoulder**
## What's this do?
Runs prettier on our codebase, which in turn helps clean up our tests

### CODE REVIEW

**Review by jayjayjpg — APPROVED** [review]
Thank you for the nice cleanup, this reads great! :sparkles:

**Comment by brettgoulder** [comment]
Miss you all!

**Comment by brettgoulder** [comment]
I'd close this out by the way, things have changed since then.

**Comment by jayjayjpg** [comment]
@brettgoulder We miss you as well and thank you for checking in! I'll close out the PR then and thank you @raulb for helping with our stale PRs!

**Pull request closed without merging**
